fix: disable nightly build

diff --git a/.github/workflows/mr-ci.yaml b/.github/workflows/mr-ci.yaml
--- a/.github/workflows/mr-ci.yaml
+++ b/.github/workflows/mr-ci.yaml
@@ -8,15 +8,6 @@ on:
     branches: [ "main", "develop", "release-v*.*" ]
   pull_request:
     branches: [ "main", "develop", "release-v*.*" ]
-  schedule:
-    - cron: "0 1 * * *" # UTC+8 09:00
-  workflow_dispatch:
-    inputs:
-      mrci_run:
-        description: 'MRCI run or not'
-        required: true
-        type: boolean
-        default: false
 
 jobs:
 
@@ -127,101 +118,101 @@ jobs:
           trigger_workflow: true
           wait_workflow: true
 
-  Build-And-Deploy:
-    if: ${{ github.event_name == 'schedule' || inputs.mrci_run }}
-    runs-on: ubuntu-latest
-    needs:
-      - Sync-Code-to-Office
-      - Get-Stable-Branch
-    outputs:
-      IP: ${{ steps.get_ip_port.outputs.IP }}
-      PORT: ${{ steps.get_ip_port.outputs.PORT }}
-    steps:
-      - name: Trigger - Build Tapdata
-        uses: convictional/trigger-workflow-and-wait@v1.6.1
-        with:
-          owner: tapdata
-          repo: tapdata-application
-          github_token: ${{ secrets.TAPDATA_ENT_CICD_TOKEN }}
-          workflow_file_name: build-tapdata-op.yaml
-          ref: main
-          wait_interval: 10
-          client_payload: '{"CONNECTORS_BRANCH": "${{ needs.Get-Stable-Branch.outputs.CONNECTORS_BRANCH }}#main", "TAG_NAME": "${{ needs.Get-Stable-Branch.outputs.TAG_NAME }}"}'
-          propagate_failure: true
-          trigger_workflow: true
-          wait_workflow: true
-      - name: Trigger - Deploy Tapdata
-        uses: convictional/trigger-workflow-and-wait@v1.6.1
-        with:
-          owner: tapdata
-          repo: tapdata-application
-          github_token: ${{ secrets.TAPDATA_ENT_CICD_TOKEN }}
-          workflow_file_name: deploy-tapdata-op.yaml
-          ref: main
-          wait_interval: 10
-          client_payload: '{"TAG_NAME": "${{ needs.Get-Stable-Branch.outputs.TAG_NAME }}", "AUTO_TEST": true}'
-          propagate_failure: true
-          trigger_workflow: true
-          wait_workflow: true
-      - name: Checkout Tapdata Application
-        uses: actions/checkout@v2
-        with:
-          repository: 'tapdata/tapdata-application'
-          ref: "main"
-          token: ${{ secrets.TAPDATA_ENT_CICD_TOKEN }}
-          path: tapdata-application
-      - name: Get IP and Port
-        id: get_ip_port
-        run: |
-          bash tapdata-application/build/upgrade.sh --get-ip-port=true --version=${{ needs.Get-Stable-Branch.outputs.TAG_NAME }} --deploy-way=docker-compose
-          IP=$(cat .service_ip_port | awk -F':' '{print $1}')
-          PORT=$(cat .service_ip_port | awk -F':' '{print $2}')
-          echo "::set-output name=IP::$IP"
-          echo "::set-output name=PORT::$PORT"
-
-  TestSigma-Test:
-    if: ${{ github.event_name == 'schedule' || inputs.mrci_run }}
-    runs-on: ubuntu-latest
-    needs:
-      - Build-And-Deploy
-    steps:
-      - name: Set Action
-        if: ${{ github.event_name == 'workflow_dispatch' }}
-        run: |
-          echo "Action=workflow_dispatch" >> $GITHUB_ENV
-      - name: Set Action
-        if: ${{ github.event_name == 'schedule' }}
-        run: |
-          echo "Action=schedule" >> $GITHUB_ENV
-      - name: Trigger - Deploy Tapdata
-        uses: convictional/trigger-workflow-and-wait@v1.6.1
-        with:
-          owner: tapdata
-          repo: tapdata-application
-          github_token: ${{ secrets.TAPDATA_ENT_CICD_TOKEN }}
-          workflow_file_name: testsigma.yaml
-          ref: main
-          wait_interval: 10
-          client_payload: '{"IP": "${{ needs.Build-And-Deploy.outputs.IP }}", "PORT": "${{ needs.Build-And-Deploy.outputs.PORT }}", "Action": "${{ env.Action }}"}'
-          propagate_failure: true
-          trigger_workflow: true
-          wait_workflow: true
-
-  CLOSE_ENV:
-    if: ${{ github.event_name == 'schedule' || failure() || inputs.mrci_run }}
-    runs-on: ubuntu-latest
-    needs:
-      - TestSigma-Test
-      - Get-Stable-Branch
-    steps:
-      - name: Checkout Tapdata Application
-        uses: actions/checkout@v2
-        with:
-          repository: 'tapdata/tapdata-application'
-          ref: "main"
-          token: ${{ secrets.TAPDATA_ENT_CICD_TOKEN }}
-          path: tapdata-application
-      - name: Close Test Env
-        id: get_ip_port
-        run: |
-          bash tapdata-application/build/upgrade.sh --delete-env=${{ needs.Get-Stable-Branch.outputs.TAG_NAME }} --delete-env-tag=true
+#  Build-And-Deploy:
+#    if: ${{ github.event_name == 'schedule' || inputs.mrci_run }}
+#    runs-on: ubuntu-latest
+#    needs:
+#      - Sync-Code-to-Office
+#      - Get-Stable-Branch
+#    outputs:
+#      IP: ${{ steps.get_ip_port.outputs.IP }}
+#      PORT: ${{ steps.get_ip_port.outputs.PORT }}
+#    steps:
+#      - name: Trigger - Build Tapdata
+#        uses: convictional/trigger-workflow-and-wait@v1.6.1
+#        with:
+#          owner: tapdata
+#          repo: tapdata-application
+#          github_token: ${{ secrets.TAPDATA_ENT_CICD_TOKEN }}
+#          workflow_file_name: build-tapdata-op.yaml
+#          ref: main
+#          wait_interval: 10
+#          client_payload: '{"CONNECTORS_BRANCH": "${{ needs.Get-Stable-Branch.outputs.CONNECTORS_BRANCH }}#main", "TAG_NAME": "${{ needs.Get-Stable-Branch.outputs.TAG_NAME }}"}'
+#          propagate_failure: true
+#          trigger_workflow: true
+#          wait_workflow: true
+#      - name: Trigger - Deploy Tapdata
+#        uses: convictional/trigger-workflow-and-wait@v1.6.1
+#        with:
+#          owner: tapdata
+#          repo: tapdata-application
+#          github_token: ${{ secrets.TAPDATA_ENT_CICD_TOKEN }}
+#          workflow_file_name: deploy-tapdata-op.yaml
+#          ref: main
+#          wait_interval: 10
+#          client_payload: '{"TAG_NAME": "${{ needs.Get-Stable-Branch.outputs.TAG_NAME }}", "AUTO_TEST": true}'
+#          propagate_failure: true
+#          trigger_workflow: true
+#          wait_workflow: true
+#      - name: Checkout Tapdata Application
+#        uses: actions/checkout@v2
+#        with:
+#          repository: 'tapdata/tapdata-application'
+#          ref: "main"
+#          token: ${{ secrets.TAPDATA_ENT_CICD_TOKEN }}
+#          path: tapdata-application
+#      - name: Get IP and Port
+#        id: get_ip_port
+#        run: |
+#          bash tapdata-application/build/upgrade.sh --get-ip-port=true --version=${{ needs.Get-Stable-Branch.outputs.TAG_NAME }} --deploy-way=docker-compose
+#          IP=$(cat .service_ip_port | awk -F':' '{print $1}')
+#          PORT=$(cat .service_ip_port | awk -F':' '{print $2}')
+#          echo "::set-output name=IP::$IP"
+#          echo "::set-output name=PORT::$PORT"
+#
+#  TestSigma-Test:
+#    if: ${{ github.event_name == 'schedule' || inputs.mrci_run }}
+#    runs-on: ubuntu-latest
+#    needs:
+#      - Build-And-Deploy
+#    steps:
+#      - name: Set Action
+#        if: ${{ github.event_name == 'workflow_dispatch' }}
+#        run: |
+#          echo "Action=workflow_dispatch" >> $GITHUB_ENV
+#      - name: Set Action
+#        if: ${{ github.event_name == 'schedule' }}
+#        run: |
+#          echo "Action=schedule" >> $GITHUB_ENV
+#      - name: Trigger - Deploy Tapdata
+#        uses: convictional/trigger-workflow-and-wait@v1.6.1
+#        with:
+#          owner: tapdata
+#          repo: tapdata-application
+#          github_token: ${{ secrets.TAPDATA_ENT_CICD_TOKEN }}
+#          workflow_file_name: testsigma.yaml
+#          ref: main
+#          wait_interval: 10
+#          client_payload: '{"IP": "${{ needs.Build-And-Deploy.outputs.IP }}", "PORT": "${{ needs.Build-And-Deploy.outputs.PORT }}", "Action": "${{ env.Action }}"}'
+#          propagate_failure: true
+#          trigger_workflow: true
+#          wait_workflow: true
+#
+#  CLOSE_ENV:
+#    if: ${{ github.event_name == 'schedule' || failure() || inputs.mrci_run }}
+#    runs-on: ubuntu-latest
+#    needs:
+#      - TestSigma-Test
+#      - Get-Stable-Branch
+#    steps:
+#      - name: Checkout Tapdata Application
+#        uses: actions/checkout@v2
+#        with:
+#          repository: 'tapdata/tapdata-application'
+#          ref: "main"
+#          token: ${{ secrets.TAPDATA_ENT_CICD_TOKEN }}
+#          path: tapdata-application
+#      - name: Close Test Env
+#        id: get_ip_port
+#        run: |
+#          bash tapdata-application/build/upgrade.sh --delete-env=${{ needs.Get-Stable-Branch.outputs.TAG_NAME }} --delete-env-tag=true
